/**
 * admin/src/pwa-icons.unit.test.ts
 * Content assertions on the six committed PWA icon PNGs generated by
 * scripts/build-pwa-icons.ts and checked in under admin/pwa-assets/icons/.
 * Verifies real bytes on disk — not the generation script itself.
 */

import { describe, expect, it } from "bun:test";
import { join } from "node:path";
import { PWA_ICONS, PWA_ASSETS_DIR } from "./pwa.ts";

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]);
const MAX_ICON_BYTES = 60 * 1024;

describe("committed PWA icons", () => {
  it("declares exactly six icons", () => {
    expect(PWA_ICONS.length).toBe(6);
  });

  for (const icon of PWA_ICONS) {
    describe(icon.filename, () => {
      it("exists on disk", async () => {
        const file = Bun.file(join(PWA_ASSETS_DIR, "icons", icon.filename));
        expect(await file.exists()).toBe(true);
      });

      it("starts with the PNG magic bytes", async () => {
        const file = Bun.file(join(PWA_ASSETS_DIR, "icons", icon.filename));
        const bytes = new Uint8Array(await file.arrayBuffer());
        const header = Buffer.from(bytes.subarray(0, 8));
        expect(header.equals(PNG_MAGIC)).toBe(true);
      });

      it("is under 60KB", async () => {
        const file = Bun.file(join(PWA_ASSETS_DIR, "icons", icon.filename));
        expect(file.size).toBeGreaterThan(0);
        expect(file.size).toBeLessThan(MAX_ICON_BYTES);
      });
    });
  }
});
