/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts/agents/{agentId}/config": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get full env bundle for an agent (owner API key or matching agent token) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Full agent env bundle — all stored vars plus computed engagement and OAuth vars */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentEnvBundle"];
          };
        };
        /** @description Unauthorized — no valid token provided */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden — agent token does not match the requested agentId */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description No env vars found for agentId */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all users */
    get: {
      parameters: {
        query?: {
          role?: "OWNER" | "MEMBER" | "AGENT";
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of user records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserList"];
          };
        };
        /** @description Invalid query parameter */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Create a new user */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateUserInput"];
        };
      };
      responses: {
        /** @description Created user record */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Email already exists */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/users/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a user by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description User record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update a user */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateUserInput"];
        };
      };
      responses: {
        /** @description Updated user record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["UserRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description User not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/accounts/clients": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all clients with engagement count */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of client records with engagement count */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClientList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Create a new client */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateClientInput"];
        };
      };
      responses: {
        /** @description Created client record */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClientDetailRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/clients/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a client by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Client record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClientDetailRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Client not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a client */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Client deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Client not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Client has engagements */
        409: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a client */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateClientInput"];
        };
      };
      responses: {
        /** @description Updated client record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ClientDetailRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Client not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/accounts/engagements": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List engagements with optional status/clientId filter */
    get: {
      parameters: {
        query?: {
          status?: "ACTIVE" | "PAUSED" | "CLOSED";
          clientId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of engagement records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["EngagementList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Create a new engagement */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateEngagementInput"];
        };
      };
      responses: {
        /** @description Created engagement record */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["EngagementRecord"];
          };
        };
        /** @description Invalid input or client not found */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/engagements/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an engagement by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Engagement record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["EngagementRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Engagement not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete an engagement */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Engagement deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Engagement not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update an engagement */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateEngagementInput"];
        };
      };
      responses: {
        /** @description Updated engagement record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["EngagementRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Engagement not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/accounts/oauth/{userId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List OAuth connections for a user */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of OAuth connection records for the user */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OAuthConnectionList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/oauth/{provider}/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a valid access token for the caller, auto-refreshing if expired. Agents resolve owner + clientId automatically. */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Valid access token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OAuthTokenResponse"];
          };
        };
        /** @description Unknown provider */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description OAuth connection not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Token refresh failed (upstream error) */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/oauth/{userId}/{provider}/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a valid access token, auto-refreshing if expired */
    get: {
      parameters: {
        query?: {
          clientId?: string;
        };
        header?: never;
        path: {
          userId: string;
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Valid access token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OAuthTokenResponse"];
          };
        };
        /** @description Unknown provider or missing Google credentials */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden — non-admin caller may only request their own userId */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description OAuth connection not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Token refresh failed (upstream error) */
        502: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/oauth/{userId}/{provider}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get an OAuth connection by userId and provider */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OAuth connection record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OAuthConnectionRecord"];
          };
        };
        /** @description Unknown provider */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description OAuth connection not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete an OAuth connection */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          provider: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description OAuth connection deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unknown provider */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description OAuth connection not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/connections": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List connections (no tokens) with optional provider/clientId filter */
    get: {
      parameters: {
        query?: {
          provider?: string;
          clientId?: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of connection records (no tokens) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ConnectionList"];
          };
        };
        /** @description Unknown provider */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/connections/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a connection by id */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Connection deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Cannot delete the only default connection */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Connection not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Patch a connection — assign a clientId */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["PatchConnectionInput"];
        };
      };
      responses: {
        /** @description Updated connection record (no tokens) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ConnectionRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Connection not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/accounts/connections/{id}/token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a valid access token for a connection (service-to-service) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Valid access token */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["OAuthTokenResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Connection not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Token refresh failed */
        503: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/users/{userId}/tokens": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List tokens for a user (no raw token values) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of user token records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentTokenList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Create a scoped API token for a user (admin scope required) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateAgentTokenInput"];
        };
      };
      responses: {
        /** @description Created token — raw value shown once */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentTokenCreatedResponse"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden — admin scope required */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description userId not found, or clientId not found */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/users/{userId}/tokens/{tokenId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Revoke a user token */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          userId: string;
          tokenId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Token revoked */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Token not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/users/tokens/validate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Validate a raw user token (service-to-service) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ValidateAgentTokenInput"];
        };
      };
      responses: {
        /** @description Token is valid — returns userId and clientId */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ValidateAgentTokenResponse"];
          };
        };
        /** @description Token is invalid or revoked */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/agent-envs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all agent env vars — interceptor use only (API key auth) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All agent env vars (decrypted) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentEnvRecord"][];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/agent-envs/{agentId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all env vars for an agent (OWNER or authenticated caller) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Agent env vars (decrypted) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentEnvRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description No env vars found for agentId */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Replace all env vars for an agent (OWNER only) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpsertAgentEnvInput"];
        };
      };
      responses: {
        /** @description Updated env vars for the agent */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentEnvRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description agentId is not an AGENT user */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    /** Patch specific env vars for an agent without replacing others (OWNER only) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpsertAgentEnvInput"];
        };
      };
      responses: {
        /** @description Updated env vars for the agent */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentEnvRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description agentId is not an AGENT user */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/accounts/teams": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all teams */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of team records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TeamList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Create a new team */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateTeamInput"];
        };
      };
      responses: {
        /** @description Created team record */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TeamRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/teams/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get a team by ID */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Team record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TeamRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Team not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Delete a team (cascades to TeamMember rows; User rows unchanged) */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Team deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Team not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a team (name, add/remove members) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          id: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateTeamInput"];
        };
      };
      responses: {
        /** @description Updated team record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["TeamRecord"];
          };
        };
        /** @description Invalid input */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Team not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/accounts/agents/{agentId}/crons": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List cron jobs for an agent */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of agent cron job records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentCronJobList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Create a cron job for an agent */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["CreateAgentCronJobInput"];
        };
      };
      responses: {
        /** @description Created cron job record */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentCronJobRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Invalid cron expression or missing delivery target */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/agents/{agentId}/crons/{cronId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a cron job */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
          cronId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Cron job deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Cron job not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Update a cron job (schedule, prompt, channel, user, silent, enabled, preCheck) */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
          cronId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateAgentCronJobInput"];
        };
      };
      responses: {
        /** @description Updated cron job record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentCronJobRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Cron job not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
  "/accounts/crons/enabled": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all enabled cron jobs across all agents — interceptor use only (API key auth) */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description All enabled cron job records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentCronJobList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden — agent tokens cannot access this endpoint */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/agents/{agentId}/crons/reconcile-system": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reconcile system crons for an agent — interceptor use only (API key auth) */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Reconciliation summary */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["ReconcileSystemCronsResult"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Forbidden — agent tokens cannot access this endpoint */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/agents/{agentId}/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List tool patterns for an agent */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Array of agent tool records */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentToolList"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    put?: never;
    /** Add a tool pattern for an agent */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["AddAgentToolInput"];
        };
      };
      responses: {
        /** @description Created or re-enabled tool record */
        201: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentToolRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Invalid input */
        422: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/agents/{agentId}/tools/{toolId}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete a tool pattern */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
          toolId: string;
        };
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Tool deleted */
        204: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Tool not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    options?: never;
    head?: never;
    /** Enable or disable a tool pattern */
    patch: {
      parameters: {
        query?: never;
        header?: never;
        path: {
          agentId: string;
          toolId: string;
        };
        cookie?: never;
      };
      requestBody?: {
        content: {
          "application/json": components["schemas"]["UpdateAgentToolInput"];
        };
      };
      responses: {
        /** @description Updated tool record */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["AgentToolRecord"];
          };
        };
        /** @description Unauthorized */
        401: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
        /** @description Tool not found */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            "application/json": components["schemas"]["Error"];
          };
        };
      };
    };
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AgentEnvBundle: {
      env: {
        [key: string]: string;
      };
      agentUserId: string;
      allowedTools: string[];
    };
    Error: {
      error: string;
    };
    UserList: components["schemas"]["UserRecord"][];
    UserRecord: {
      id: string;
      name: string;
      /** Format: email */
      email: string;
      slackId: string | null;
      /** @enum {string} */
      role: "OWNER" | "MEMBER" | "AGENT";
      workingHoursStart: string;
      workingHoursEnd: string;
      timezone: string;
      mercuryCounterparty: string | null;
      ownerUserId: string | null;
      clientId: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateUserInput: {
      name: string;
      /** Format: email */
      email: string;
      slackId?: string;
      /** @enum {string} */
      role?: "OWNER" | "MEMBER" | "AGENT";
      workingHoursStart?: string;
      workingHoursEnd?: string;
      timezone?: string;
      ownerUserId?: string | null;
      clientId?: string | null;
    };
    UpdateUserInput: {
      name?: string;
      slackId?: string | null;
      /** @enum {string} */
      role?: "OWNER" | "MEMBER" | "AGENT";
      workingHoursStart?: string;
      workingHoursEnd?: string;
      timezone?: string;
      mercuryCounterparty?: string | null;
      ownerUserId?: string | null;
      clientId?: string | null;
    };
    ClientList: components["schemas"]["ClientRecord"][];
    ClientRecord: {
      id: string;
      name: string;
      email: string | null;
      teamId: string | null;
      engagementCount: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    ClientDetailRecord: {
      id: string;
      name: string;
      email: string | null;
      teamId: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateClientInput: {
      name: string;
      /** Format: email */
      email?: string;
      teamId?: string;
    };
    UpdateClientInput: {
      name?: string;
      /** Format: email */
      email?: string | null;
      teamId?: string | null;
    };
    EngagementList: components["schemas"]["EngagementRecord"][];
    EngagementRecord: {
      id: string;
      clientId: string;
      name: string;
      hourlyRate: number;
      /** @enum {string} */
      engagement_type:
        | "llc_auto"
        | "llc_manual"
        | "llc_external"
        | "partner_direct";
      /** @enum {string|null} */
      billingPeriod:
        | "WEEKLY"
        | "BI_WEEKLY"
        | "FOUR_WEEKLY"
        | "SEMI_MONTHLY"
        | "MONTHLY"
        | null;
      billingDay: string | null;
      contractedHours: number | null;
      billingAddress: string | null;
      contactName: string | null;
      billingEmail: string | null;
      ccEmails: string[];
      defaultTask: string | null;
      extraLineItems: {
        description: string;
        amount: number;
      }[];
      notes: string | null;
      weeklyHoursCap: number | null;
      togglProjectId: number | null;
      /** Format: date-time */
      startDate: string;
      /** Format: date-time */
      endDate: string | null;
      /** @enum {string} */
      status: "ACTIVE" | "PAUSED" | "CLOSED";
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateEngagementInput: {
      clientId: string;
      name: string;
      hourlyRate: number;
      /** Format: date-time */
      startDate: string;
      /** @enum {string} */
      engagement_type?:
        | "llc_auto"
        | "llc_manual"
        | "llc_external"
        | "partner_direct";
      /** @enum {string|null} */
      billingPeriod?:
        | "WEEKLY"
        | "BI_WEEKLY"
        | "FOUR_WEEKLY"
        | "SEMI_MONTHLY"
        | "MONTHLY"
        | null;
      billingDay?: string;
      contractedHours?: number;
      billingAddress?: string;
      contactName?: string;
      /** Format: email */
      billingEmail?: string;
      ccEmails?: string[];
      defaultTask?: string;
      extraLineItems?: {
        description: string;
        amount: number;
      }[];
      notes?: string;
      weeklyHoursCap?: number;
      togglProjectId?: number;
      /** Format: date-time */
      endDate?: string;
      /** @enum {string} */
      status?: "ACTIVE" | "PAUSED" | "CLOSED";
    };
    UpdateEngagementInput: {
      name?: string;
      hourlyRate?: number;
      /** @enum {string} */
      engagement_type?:
        | "llc_auto"
        | "llc_manual"
        | "llc_external"
        | "partner_direct";
      /** @enum {string|null} */
      billingPeriod?:
        | "WEEKLY"
        | "BI_WEEKLY"
        | "FOUR_WEEKLY"
        | "SEMI_MONTHLY"
        | "MONTHLY"
        | null;
      billingDay?: string | null;
      contractedHours?: number | null;
      billingAddress?: string | null;
      contactName?: string | null;
      /** Format: email */
      billingEmail?: string | null;
      ccEmails?: string[];
      defaultTask?: string | null;
      extraLineItems?: {
        description: string;
        amount: number;
      }[];
      notes?: string | null;
      weeklyHoursCap?: number | null;
      togglProjectId?: number | null;
      /** Format: date-time */
      endDate?: string | null;
      /** @enum {string} */
      status?: "ACTIVE" | "PAUSED" | "CLOSED";
    };
    OAuthConnectionList: components["schemas"]["OAuthConnectionRecord"][];
    OAuthConnectionRecord: {
      id: string;
      userId: string;
      /** @enum {string} */
      provider: "GOOGLE" | "SLACK";
      externalId: string;
      title: string | null;
      clientId: string | null;
      accessToken: string;
      refreshToken: string;
      /** Format: date-time */
      expiresAt: string;
      scopes: string[];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    OAuthTokenResponse: {
      accessToken: string;
      /** Format: date-time */
      expiresAt: string;
    };
    ConnectionList: components["schemas"]["ConnectionRecord"][];
    ConnectionRecord: {
      id: string;
      userId: string;
      /** @enum {string} */
      provider: "GOOGLE" | "SLACK";
      externalId: string;
      title: string | null;
      clientId: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    PatchConnectionInput: {
      clientId?: string | null;
    };
    AgentTokenCreatedResponse: {
      id: string;
      userId: string;
      clientId: string;
      label: string | null;
      /** Format: date-time */
      createdAt: string;
      rawToken: string;
    };
    CreateAgentTokenInput: {
      clientId: string;
      label?: string;
    };
    AgentTokenList: components["schemas"]["AgentTokenRecord"][];
    AgentTokenRecord: {
      id: string;
      userId: string;
      clientId: string;
      label: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      revokedAt: string | null;
    };
    ValidateAgentTokenResponse: {
      userId: string;
      clientId: string;
    };
    ValidateAgentTokenInput: {
      token: string;
    };
    AgentEnvRecord: {
      agentId: string;
      env: {
        [key: string]: string;
      };
      /** Format: date-time */
      updatedAt: string;
    };
    UpsertAgentEnvInput: {
      env: {
        [key: string]: string;
      };
    };
    TeamList: components["schemas"]["TeamRecord"][];
    TeamRecord: {
      id: string;
      name: string;
      domain: string | null;
      mercuryAccountId: string | null;
      memberIds: string[];
      /** Format: date-time */
      createdAt: string;
    };
    CreateTeamInput: {
      name: string;
      domain?: string;
      mercuryAccountId?: string;
      memberIds: string[];
    };
    UpdateTeamInput: {
      name?: string;
      domain?: string | null;
      mercuryAccountId?: string | null;
      addMemberIds?: string[];
      removeMemberIds?: string[];
    };
    AgentCronJobList: components["schemas"]["AgentCronJobRecord"][];
    AgentCronJobRecord: {
      id: string;
      agentId: string;
      schedule: string;
      prompt: string;
      channel: string | null;
      user: string | null;
      silent: boolean;
      enabled: boolean;
      /** @description Optional pre-check script. Runs before Claude; its stdout becomes the prompt if exit code is 0 and output is non-empty — otherwise the cron tick is skipped. Formats: "plugin:script.ts" (resolved from plugin install path), "./relative.ts" or "../relative.ts" (resolved against agent workspace root), or "/absolute/path.ts". */
      preCheck: string | null;
      name: string | null;
      system: boolean;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    CreateAgentCronJobInput: {
      schedule: string;
      prompt: string;
      channel?: string | null;
      user?: string | null;
      silent?: boolean;
      enabled?: boolean;
      /** @description Optional pre-check script. Runs before Claude; its stdout becomes the prompt if exit code is 0 and output is non-empty — otherwise the cron tick is skipped. Formats: "plugin:script.ts" (resolved from plugin install path), "./relative.ts" or "../relative.ts" (resolved against agent workspace root), or "/absolute/path.ts". */
      preCheck?: string | null;
      name?: string | null;
    };
    UpdateAgentCronJobInput: {
      enabled?: boolean;
      schedule?: string;
      prompt?: string;
      channel?: string | null;
      user?: string | null;
      silent?: boolean;
      /** @description Optional pre-check script. Runs before Claude; its stdout becomes the prompt if exit code is 0 and output is non-empty — otherwise the cron tick is skipped. Formats: "plugin:script.ts" (resolved from plugin install path), "./relative.ts" or "../relative.ts" (resolved against agent workspace root), or "/absolute/path.ts". */
      preCheck?: string | null;
    };
    ReconcileSystemCronsResult: {
      created: number;
      updated: number;
      deleted: number;
    };
    AgentToolList: components["schemas"]["AgentToolRecord"][];
    AgentToolRecord: {
      id: string;
      agentId: string;
      pattern: string;
      enabled: boolean;
      /** Format: date-time */
      createdAt: string;
    };
    AddAgentToolInput: {
      pattern: string;
    };
    UpdateAgentToolInput: {
      enabled: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
