/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agents/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile all agents' K8s state
         * @description Admin-only. Reconciles Kubernetes Deployment state against all managed (non-self-hosted) agents in the DB, returning counts of recreated/updated deployments plus any orphaned deployments or per-agent failures.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reconciliation summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconcileAgentsResult"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/provision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Provision an agent's K8s workload
         * @description Admin-only. Provisions or re-provisions the Kubernetes workload for a single managed agent — idempotent, safe to call on an already-provisioned agent. For self-hosted agents, returns `{ skipped: true, reason: "self-hosted" }` with no K8s changes.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent provisioned (or already-provisioned — idempotent), or skipped for self-hosted agents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProvisionAgentResult"] | components["schemas"]["ProvisionSkippedResult"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get an agent
         * @description Admin-only. Returns the full agent record including `selfHosted`, `repos`, `reviewAuthorAllowlist`, `patchAuthorAllowlist`, `restrictSlackToMembers`, `typeName`, and `missingRequiredEnv` — required env keys declared by the agent's type manifest with no corresponding AgentEnv row yet (informational only).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Full agent record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetAgentResult"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * Delete an agent
         * @description Admin-only. Runs the full deleteAgentFully() teardown: deprovisions the K8s workload, revokes task-store and chat-service tokens, deletes chat threads, and — if an `xoxpToken` is supplied — deletes the Slack app. The Agent row (and its cascade-deleted child records) is deleted last, only if every automatable step succeeded; `agentDeleted: false` means the row was preserved and the call is safe to retry.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["DeleteAgentBody"];
                };
            };
            responses: {
                /** @description Delete outcome — agentDeleted is false when a cleanup step failed; the Agent row is preserved for retry */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DeleteAgentResult"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update an agent
         * @description Admin-only. Updates `selfHosted`, `repos`, `reviewAuthorAllowlist`, `patchAuthorAllowlist`, `restrictSlackToMembers`, and/or `slackId`. `typeName` is not updatable via this route. Returns the updated agent, including a `warning` field when `restrictSlackToMembers` is set true on an agent with zero members.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PatchAgentBody"];
                };
            };
            responses: {
                /** @description Agent updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GetAgentResult"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all agents
         * @description Admin-only. Returns every agent's `id`, `name`, `selfHosted`, and `typeName` — used for metrics name resolution.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of agents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentSummary"][];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/envs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get env vars
         * @description Returns the agent's env vars. Non-secret values are decrypted; values flagged secret are masked as `***` and their keys listed in `secretKeys`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Decrypted env vars */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentEnvResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Replace all env vars
         * @description Bulk-replaces all env vars for the agent atomically. Values are stored encrypted (AES-256-GCM).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AgentEnvBody"];
                };
            };
            responses: {
                /** @description Env vars replaced */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update specific env vars
         * @description Updates only the specified keys, leaving other existing env vars untouched.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["AgentEnvPatchBody"];
                };
            };
            responses: {
                /** @description Env vars updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Ok"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/agents/{id}/envs/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete an env var
         * @description Deletes a single env var by key.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    key: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Key deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/crons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List agent cron jobs
         * @description Returns the agent's cron jobs as a plain array (not wrapped), used by the agent harness's scheduler. Returns 404 if the agent doesn't exist.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of cron jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentCronJob"][];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeError"];
                    };
                };
                /** @description Agent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeError"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a cron job
         * @description Creates a cron job for the agent. `channel` and `user` are mutually exclusive delivery targets. Returns the created job including system-managed read-only fields (`id`, `system`, `parentCronId`, `createdAt`, `updatedAt`) — `parentCronId` is never settable by the caller.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAgentCronJobBody"];
                };
            };
            responses: {
                /** @description Cron job created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/crons/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reconcile system crons
         * @description Reconciles the agent's system crons against the cron list declared by its Agent Type manifest. Runs in three passes within a single transaction: create-or-update matched-by-name system crons (preserving IDs so run history survives), link/unlink parent-child cron relationships, and delete orphaned system crons no longer in the manifest. Called automatically on agent startup; returns created/updated/deleted counts.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reconciliation summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReconcileCronResult"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/crons/{cronId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a cron job
         * @description Deletes a cron job. System crons (`system: true`) cannot be deleted and return 403.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    cronId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cron job deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a cron job
         * @description Updates a cron job. `schedule` and `prompt` must be provided together for a content update; `enabled` and `preCheck` are orthogonal and may be sent alone or combined with any other field. At least one field must be present — an empty body returns 400. System crons (`system: true`) cannot be updated and return 403.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    cronId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PatchAgentCronJobBody"];
                };
            };
            responses: {
                /** @description Cron job updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/agents/{id}/crons/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cron jobs with run summary
         * @description Returns each cron job's last-run timestamp, outcome, and today's run count alongside its config — without full prompt text. Useful for dashboards.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of cron jobs with run summary */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronsWithSummaryWrapper"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/crons/{cronId}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List cron runs
         * @description Returns a paginated list of runs for a cron job (`limit` default 20, `offset` default 0). `itemId` and `phaseId` are optional server-side filters that combine with AND when both are supplied.
         */
        get: {
            parameters: {
                query?: {
                    limit?: string;
                    offset?: string;
                    itemId?: string;
                    phaseId?: string;
                };
                header?: never;
                path: {
                    id: string;
                    cronId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of cron runs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronRunsList"];
                    };
                };
                /** @description Cron job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create a cron run record
         * @description Records the start of a cron job execution, including optional skip/outcome data and dispatch attribution (`itemType`/`itemId`, write-once at creation).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    cronId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAgentCronRunBody"];
                };
            };
            responses: {
                /** @description Run record created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronRunWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Cron job not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/crons/{cronId}/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a cron run record
         * @description Records completion data after a run finishes — `completedAt`, `outcome`, `error`, `skipped`, `skipReason`, `sessionId`, and `modelBreakdown` (per-model token/cost entries, upserted per `[cronRunId, model]`). At least one field must be provided.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    cronId: string;
                    runId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PatchAgentCronRunBody"];
                };
            };
            responses: {
                /** @description Run record updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PatchCronRunWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Run not found or not owned by agent */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/agents/{id}/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tool patterns
         * @description Returns every allowed-tool entry for the agent, each with `id`, `pattern`, and `enabled`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tool patterns */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToolsWrapper"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add a tool pattern
         * @description Adds an allowed-tool entry — a glob or exact Claude Code tool name (e.g. "Read", "Bash", "mcp__*") the agent can call.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAgentToolBody"];
                };
            };
            responses: {
                /** @description Tool added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToolWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/tools/{toolId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove a tool pattern
         * @description Deletes a tool entry from the agent's allowed-tools list.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    toolId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Tool removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Enable or disable a tool pattern
         * @description Updates a tool entry's `pattern` and/or `enabled` state.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    toolId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PatchAgentToolBody"];
                };
            };
            responses: {
                /** @description Tool toggled */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ToolWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/agents/{id}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List API tokens
         * @description Returns token metadata (hash excluded) for the agent — raw token values are never returned after creation.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of token metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TokensWrapper"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create an API token
         * @description Creates a per-agent bearer token for scoped API access. The raw token value is returned once in this response — only its SHA-256 hash is persisted, so it must be saved immediately.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAgentTokenBody"];
                };
            };
            responses: {
                /** @description Token created (raw value returned once) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CreateAgentTokenResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke an API token
         * @description Soft-deletes the token by setting `revokedAt`.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    tokenId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Token revoked */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List plugins
         * @description Returns every plugin installed for the agent.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of plugins */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PluginsWrapper"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Install a plugin
         * @description Adds a Claude Code marketplace plugin for the agent.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateAgentPluginBody"];
                };
            };
            responses: {
                /** @description Plugin added */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PluginWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        /**
         * Remove a plugin
         * @description Removes the plugin identified by the required `name` query param.
         */
        delete: {
            parameters: {
                query: {
                    name: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Plugin removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * Update a plugin
         * @description Re-upserts the plugin identified by the required `name` query param with a new `version` and/or `enabled` state. Uses a query param rather than a path segment because a canonical plugin spec like "my-plugin@org/my-marketplace" can contain a literal "/" that would break path matching.
         */
        patch: {
            parameters: {
                query: {
                    name: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PatchAgentPluginBody"];
                };
            };
            responses: {
                /** @description Plugin version updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PluginWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/agents/all/cron-runs/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregated cron-run token stats
         * @description Admin-only. Returns token usage and cost aggregated across all agents' cron runs, broken down by agent, cron, model, day, and pipeline phase. Optional `from`/`to` ISO datetime query params bound the range.
         */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated cron-run token stats across all agents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CronRunTokenStats"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden — requires admin scope */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/chat-tokens/daily/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get aggregated chat token daily stats
         * @description Admin-only. Returns Slack chat token usage aggregated across all agents, broken down by agent, model, and day. Optional `from`/`to` YYYY-MM-DD query params bound the range.
         */
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated chat token daily stats across all agents */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatTokenStats"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden — requires admin scope */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/chat-tokens/daily": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record daily chat token usage
         * @description Atomically accumulates Slack chat token usage into the existing rows for each `(agentId, date, model)` tuple, creating them if absent. Supply a `modelBreakdown` array to split a single day's usage across multiple models. Returns the updated daily rows, one per model.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpsertChatTokenDailyBody"];
                };
            };
            responses: {
                /** @description Updated daily chat token usage rows (one per model) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentChatTokenUsageDailyByModel"][];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Agent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/work-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the latest work-queue snapshot
         * @description Returns the most recently pushed work-queue snapshot, or 404 if the agent has never pushed one.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest work-queue snapshot */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkQueueSnapshotWrapper"];
                    };
                };
                /** @description No snapshot pushed yet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Push a work-queue snapshot
         * @description Upserts the agent's single ranked work-queue snapshot (tasks/PRs across pipeline phases), overwriting any prior snapshot — there is no history.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PushWorkQueueSnapshotBody"];
                };
            };
            responses: {
                /** @description Snapshot upserted (overwrites any prior snapshot for this agent) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WorkQueueSnapshotWrapper"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get agent config bundle
         * @description Returns the agent's full runtime config bundle — decrypted env vars, allowed-tools patterns, installed plugins (with derived marketplace), scoped repos, review/patch author allowlists, and Slack membership-restriction settings. Polled by the agent harness on startup and during its config sync loop. Returns 404 if the agent doesn't exist.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Agent config bundle */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AgentConfigResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeError"];
                    };
                };
                /** @description Agent not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RuntimeError"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ReconcileAgentsResult: {
            recreated: string[];
            updated: string[];
            orphans: string[];
            failed: {
                agentId: string;
                error: string;
            }[];
        };
        Error: {
            /** @example not found */
            error: string;
        };
        ProvisionAgentResult: {
            resourceName: string;
            secretName: string;
            deploymentName: string;
        };
        ProvisionSkippedResult: {
            /** @enum {boolean} */
            skipped: true;
            reason: string;
        };
        GetAgentResult: {
            id: string;
            name: string;
            slackId?: string | null;
            selfHosted: boolean;
            repos: string[];
            reviewAuthorAllowlist: string[];
            patchAuthorAllowlist: string[];
            restrictSlackToMembers: boolean;
            typeName: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            missingRequiredEnv: string[];
            warning?: string;
        };
        PatchAgentBody: {
            /** @example U0AALR8M69X */
            slackId?: string | null;
            /** @example false */
            selfHosted?: boolean;
            /**
             * @example [
             *       "my-org/my-repo"
             *     ]
             */
            repos?: string[];
            /**
             * @example [
             *       "octocat"
             *     ]
             */
            reviewAuthorAllowlist?: string[];
            /**
             * @example [
             *       "octocat"
             *     ]
             */
            patchAuthorAllowlist?: string[];
            /** @example false */
            restrictSlackToMembers?: boolean;
        };
        FailedStep: {
            /** @example k8s */
            step: string;
            /** @example k8s API timeout */
            error: string;
        };
        ManualStep: {
            /** @example GH_TOKEN */
            key: string;
            /** @example GH_TOKEN was not automatically revoked — rotate or revoke it manually. */
            message: string;
        };
        DeleteAgentResult: {
            /** @example true */
            agentDeleted: boolean;
            /**
             * @example [
             *       "k8s",
             *       "task-store-tokens",
             *       "chat-service-tokens-and-threads"
             *     ]
             */
            completed: string[];
            failed: components["schemas"]["FailedStep"][];
            manualStepsRequired: components["schemas"]["ManualStep"][];
        };
        DeleteAgentBody: {
            /** @example xoxp-user-token */
            xoxpToken?: string;
        };
        AgentSummary: {
            /** @example clx1234567890 */
            id: string;
            /** @example Bodhi */
            name: string;
            /** @example false */
            selfHosted: boolean;
            /** @example coding */
            typeName: string;
        };
        Ok: {
            /** @enum {boolean} */
            ok: true;
        };
        AgentEnvBody: {
            [key: string]: string;
        };
        AgentEnvResponse: {
            /**
             * @example {
             *       "MY_VAR": "value"
             *     }
             */
            env: {
                [key: string]: string;
            };
            /**
             * @example [
             *       "MY_SECRET"
             *     ]
             */
            secretKeys: string[];
        };
        AgentEnvPatchBody: {
            /**
             * @example {
             *       "MY_VAR": "value"
             *     }
             */
            env: {
                [key: string]: string;
            };
            /**
             * @example [
             *       "MY_SECRET"
             *     ]
             */
            secretKeys?: string[];
        };
        AgentCronJob: {
            /** @example clx1234567890 */
            id: string;
            /** @example clx1234567890 */
            agentId: string;
            /** @example 0 9 * * 1-5 */
            schedule: string;
            /** @example Run the morning brief. */
            prompt: string;
            /** @example C01234567 */
            channel: string | null;
            /** @example U0AALR8M69X */
            user: string | null;
            /** @example false */
            silent: boolean;
            /** @example true */
            enabled: boolean;
            /** @example shipwright:check-dev-task.ts */
            preCheck: string | null;
            /** @example morning-brief */
            name: string | null;
            /** @example false */
            system: boolean;
            /** @example null */
            parentCronId: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        CronWrapper: {
            cron: components["schemas"]["AgentCronJob"];
        };
        CreateAgentCronJobBody: {
            /** @example 0 9 * * 1-5 */
            schedule: string;
            /** @example Run the morning brief. */
            prompt: string;
            /** @example C01234567 */
            channel?: string | null;
            /** @example U0AALR8M69X */
            user?: string | null;
            /** @example false */
            silent?: boolean;
            /** @example true */
            enabled?: boolean;
            /** @example shipwright:check-dev-task.ts */
            preCheck?: string | null;
            /** @example morning-brief */
            name?: string | null;
        };
        ReconcileCronResult: {
            created: number;
            updated: number;
            deleted: number;
        };
        PatchAgentCronJobBody: {
            /** @example 0 9 * * 1-5 */
            schedule?: string;
            /** @example Run the morning brief. */
            prompt?: string;
            /** @example C01234567 */
            channel?: string | null;
            /** @example U0AALR8M69X */
            user?: string | null;
            /** @example false */
            silent?: boolean;
            /** @example shipwright:check-dev-task.ts */
            preCheck?: string | null;
            /** @example true */
            enabled?: boolean;
        };
        /** @example null */
        CronRunLastRun: {
            /**
             * Format: date-time
             * @example 2026-01-01T08:00:00.000Z
             */
            startedAt: string;
            /**
             * Format: date-time
             * @example null
             */
            completedAt: string | null;
            /** @example false */
            skipped: boolean;
            /** @example success */
            outcome: string | null;
        } | null;
        AgentCronJobWithRunSummary: components["schemas"]["AgentCronJob"] & {
            lastRun: components["schemas"]["CronRunLastRun"];
            /** @example 3 */
            runCountToday: number;
        };
        CronsWithSummaryWrapper: {
            crons: components["schemas"]["AgentCronJobWithRunSummary"][];
        };
        ModelBreakdownEntry: {
            /** @example claude-sonnet-4-5 */
            model: string;
            /**
             * @default 0
             * @example 200
             */
            inputTokens: number;
            /**
             * @default 0
             * @example 100
             */
            outputTokens: number;
            /**
             * @default 0
             * @example 8
             */
            cacheReadTokens: number;
            /**
             * @default 0
             * @example 4
             */
            cacheCreationTokens: number;
            /**
             * @default 0
             * @example 0.002
             */
            costUsd: number;
        };
        AgentCronRun: {
            /** @example clx1234567890 */
            id: string;
            /** @example clx0987654321 */
            cronId: string;
            /** @example clx1234567890 */
            agentId: string;
            /**
             * Format: date-time
             * @example 2026-01-01T08:00:00.000Z
             */
            startedAt: string;
            /**
             * Format: date-time
             * @example 2026-01-01T08:00:05.000Z
             */
            completedAt: string | null;
            /** @example false */
            skipped: boolean;
            /** @example pre-check returned false */
            skipReason: string | null;
            /** @example success */
            outcome: string | null;
            /** @example null */
            error: string | null;
            /**
             * @description Child AgentCronJob id (FK) of the pipeline phase this run served (dev-task/review/patch/deploy). Null for legacy five-job crons or ticks with no phase attribution.
             * @example clx0987654321
             */
            phaseId: string | null;
            /**
             * @description Work item type this run was dispatched against ("task" | "pr"). Null when the tick had no dispatch (skipped tick, empty queue).
             * @example task
             */
            itemType: string | null;
            /**
             * @description Work item id this run was dispatched against (e.g. "WLS-2.2" or "acme/x#123"). Null when the tick had no dispatch.
             * @example WLS-2.2
             */
            itemId: string | null;
            /** @example 1234 */
            inputTokens: number | null;
            /** @example 567 */
            outputTokens: number | null;
            /** @example 89 */
            cacheReadTokens: number | null;
            /** @example 10 */
            cacheCreationTokens: number | null;
            /**
             * @description Agent session id this run was executed under. Null for runs with no recorded session.
             * @example session-abc-123
             */
            sessionId: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T08:00:00.000Z
             */
            createdAt: string;
            modelBreakdown?: components["schemas"]["ModelBreakdownEntry"][];
        };
        CronRunWrapper: {
            run: components["schemas"]["AgentCronRun"];
        };
        CreateAgentCronRunBody: {
            /**
             * Format: date-time
             * @example 2026-01-01T08:00:00.000Z
             */
            startedAt: string;
            /**
             * Format: date-time
             * @example null
             */
            completedAt?: string | null;
            /** @example false */
            skipped?: boolean;
            /** @example pre-check returned false */
            skipReason?: string | null;
            /** @example success */
            outcome?: string | null;
            /** @example null */
            error?: string | null;
            /**
             * @description Child AgentCronJob id (FK) of the pipeline phase this run served (dev-task/review/patch/deploy)
             * @example clx0987654321
             */
            phaseId?: string | null;
            /**
             * @description Work item type this run was dispatched against ("task" | "pr")
             * @example task
             */
            itemType?: string | null;
            /**
             * @description Work item id this run was dispatched against (e.g. "WLS-2.2" or "acme/x#123")
             * @example WLS-2.2
             */
            itemId?: string | null;
        };
        CronRunsList: {
            items: components["schemas"]["AgentCronRun"][];
            /** @example 42 */
            total: number;
            /** @example 20 */
            limit: number;
            /** @example 0 */
            offset: number;
        };
        PatchCronRunWrapper: {
            run: components["schemas"]["AgentCronRun"];
        };
        PatchAgentCronRunBody: {
            /**
             * Format: date-time
             * @example 2026-01-01T08:05:00.000Z
             */
            completedAt?: string | null;
            /** @example success */
            outcome?: string | null;
            /** @example null */
            error?: string | null;
            /** @example false */
            skipped?: boolean;
            /** @example pre-check returned false */
            skipReason?: string | null;
            /** @example 1234 */
            inputTokens?: number | null;
            /** @example 567 */
            outputTokens?: number | null;
            /** @example 89 */
            cacheReadTokens?: number | null;
            /** @example 10 */
            cacheCreationTokens?: number | null;
            /**
             * @description Agent session id this run was executed under.
             * @example session-abc-123
             */
            sessionId?: string | null;
            /** @description Per-model token breakdown for this run */
            modelBreakdown?: components["schemas"]["ModelBreakdownEntry"][];
        };
        AgentTool: {
            /** @example clx1234567890 */
            id: string;
            /** @example clx1234567890 */
            agentId: string;
            /** @example Read */
            pattern: string;
            /** @example true */
            enabled: boolean;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        ToolWrapper: {
            tool: components["schemas"]["AgentTool"];
        };
        CreateAgentToolBody: {
            /** @example Bash */
            pattern: string;
        };
        ToolsWrapper: {
            tools: components["schemas"]["AgentTool"][];
        };
        PatchAgentToolBody: {
            /** @example false */
            enabled: boolean;
        };
        AgentToken: {
            /** @example clx1234567890 */
            id: string;
            /** @example clx1234567890 */
            agentId: string;
            /** @example ci-runner */
            label?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example null
             */
            revokedAt?: string | null;
        };
        CreateAgentTokenResponse: {
            token: components["schemas"]["AgentToken"];
            /** @example swt_v1_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx */
            rawToken: string;
        };
        CreateAgentTokenBody: {
            /** @example ci-runner */
            label?: string;
        };
        TokensWrapper: {
            tokens: components["schemas"]["AgentToken"][];
        };
        AgentPlugin: {
            /** @example clx1234567890 */
            id: string;
            /** @example clx1234567890 */
            agentId: string;
            /** @example @shipwright/plugin */
            name: string;
            /** @example 1.2.3 */
            version?: string | null;
            /** @example true */
            enabled: boolean;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            updatedAt: string;
        };
        PluginWrapper: {
            plugin: components["schemas"]["AgentPlugin"];
        };
        CreateAgentPluginBody: {
            /** @example @shipwright/plugin */
            name: string;
            /** @example 1.2.3 */
            version?: string | null;
        };
        PluginsWrapper: {
            plugins: components["schemas"]["AgentPlugin"][];
        };
        PatchAgentPluginBody: {
            /** @example 1.3.0 */
            version?: string | null;
        };
        TokenAggregate: {
            /** @example 600 */
            input: number;
            /** @example 300 */
            output: number;
            /** @example 60 */
            cacheRead: number;
            /** @example 30 */
            cacheCreation: number;
            /** @example 990 */
            total: number;
            /** @example 0.006 */
            costUsd?: number;
        };
        KeyedTokenAggregate: components["schemas"]["TokenAggregate"] & {
            /** @example agent-id-123 */
            key: string;
        };
        DoubleKeyedTokenAggregate: components["schemas"]["TokenAggregate"] & {
            /** @example agent-id-123 */
            key1: string;
            /** @example morning-brief */
            key2: string;
            /** @example dev-task */
            phase?: string | null;
        };
        DailyTokenAggregate: components["schemas"]["TokenAggregate"] & {
            /** @example 2026-01-10 */
            period: string;
        };
        CronRunTokenStats: {
            totals: components["schemas"]["TokenAggregate"];
            byAgent: components["schemas"]["KeyedTokenAggregate"][];
            byCron: components["schemas"]["DoubleKeyedTokenAggregate"][];
            byModel: components["schemas"]["DoubleKeyedTokenAggregate"][];
            daily: components["schemas"]["DailyTokenAggregate"][];
            byCronModel: components["schemas"]["DoubleKeyedTokenAggregate"][];
            byPhase: components["schemas"]["KeyedTokenAggregate"][];
        };
        ChatTokenStats: {
            totals: components["schemas"]["TokenAggregate"];
            byAgent: components["schemas"]["KeyedTokenAggregate"][];
            byModel: components["schemas"]["DoubleKeyedTokenAggregate"][];
            daily: components["schemas"]["DailyTokenAggregate"][];
        };
        AgentChatTokenUsageDailyByModel: {
            /** @example clx1234567890 */
            id: string;
            /** @example clx1234567890 */
            agentId: string;
            /** @example 2026-01-15 */
            date: string;
            /** @example claude-sonnet-4-5 */
            model: string;
            /** @example 100 */
            inputTokens: number;
            /** @example 50 */
            outputTokens: number;
            /** @example 10 */
            cacheReadTokens: number;
            /** @example 5 */
            cacheCreationTokens: number;
            /** @example 0.0012 */
            costUsd: number;
            /**
             * Format: date-time
             * @example 2026-01-15T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-15T12:00:00.000Z
             */
            updatedAt: string;
        };
        ChatTokenModelEntry: {
            /** @example claude-sonnet-4-5 */
            model: string;
            /** @example 100 */
            inputTokens: number;
            /** @example 50 */
            outputTokens: number;
            /** @example 10 */
            cacheReadTokens: number;
            /** @example 5 */
            cacheCreationTokens: number;
            /** @example 0.0012 */
            costUsd: number;
        };
        UpsertChatTokenDailyBody: {
            /** @example 2026-01-15 */
            date: string;
            /** @description Per-model token usage increments */
            modelBreakdown: components["schemas"]["ChatTokenModelEntry"][];
        };
        RankedWorkItem: {
            /**
             * @example task
             * @enum {string}
             */
            type: "task" | "pr";
            /** @example WLS-2.2 */
            id: string;
            /** @example Add work queue snapshot endpoints */
            title?: string;
            /**
             * @example dev-task
             * @enum {string}
             */
            phase: "dev-task" | "plan" | "review" | "patch" | "deploy";
            /**
             * @description ISO timestamp
             * @example 2026-01-01T00:00:00.000Z
             */
            age: string;
        };
        AgentWorkQueueSnapshot: {
            /** @example clx1234567890 */
            id: string;
            /** @example clx1234567890 */
            agentId: string;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            computedAt: string;
            items: components["schemas"]["RankedWorkItem"][];
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        WorkQueueSnapshotWrapper: {
            snapshot: components["schemas"]["AgentWorkQueueSnapshot"];
        };
        PushWorkQueueSnapshotBody: {
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            computedAt: string;
            items: components["schemas"]["RankedWorkItem"][];
        };
        AgentConfigPlugin: {
            /** @example shipwright */
            marketplace: string;
            /** @example shipwright */
            plugin: string;
        };
        AgentConfigResponse: {
            /**
             * @example {
             *       "SLACK_BOT_TOKEN": "xoxb-..."
             *     }
             */
            env: {
                [key: string]: string;
            };
            /**
             * @example [
             *       "Read",
             *       "Write"
             *     ]
             */
            allowedTools: string[];
            plugins: components["schemas"]["AgentConfigPlugin"][];
            /**
             * @example [
             *       "org/repo1",
             *       "org/repo2"
             *     ]
             */
            repos: string[];
            /**
             * @example [
             *       "octocat"
             *     ]
             */
            reviewAuthorAllowlist: string[];
            /**
             * @example [
             *       "octocat"
             *     ]
             */
            patchAuthorAllowlist: string[];
            /** @example false */
            restrictSlackToMembers: boolean;
            /**
             * @example [
             *       "dev@example.com"
             *     ]
             */
            memberEmails: string[];
        };
        RuntimeError: {
            /** @example Not found */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
