/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tokens */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of token metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatToken"][];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new token — raw value returned exactly once */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TokenBody"];
                };
            };
            responses: {
                /** @description Created token including the one-time raw value */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatTokenWithRaw"];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a token */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked token metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatToken"];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update token label and/or agentId */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TokenBody"];
                };
            };
            responses: {
                /** @description Updated token metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChatToken"];
                    };
                };
                /** @description Bad request — token is revoked */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List threads (scoped to agentId for agent tokens) */
        get: {
            parameters: {
                query?: {
                    limit?: string;
                    offset?: string;
                    agentId?: string;
                    memberId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of threads with total count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThreadListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateThreadBody"];
                };
            };
            responses: {
                /** @description Created thread */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Thread"];
                    };
                };
                /** @description Bad request — agentId is required */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden — agent token may only create threads for itself */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get aggregated stats for a thread */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Aggregated thread stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ThreadStats"];
                    };
                };
                /** @description Forbidden — agent token may not access this thread */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Thread not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a thread by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Thread */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Thread"];
                    };
                };
                /** @description Forbidden — agent token may not access this thread */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Thread not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a thread */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted thread */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Thread"];
                    };
                };
                /** @description Forbidden — agent token may not access this thread */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Thread not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update thread title and/or memberId */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateThreadBody"];
                };
            };
            responses: {
                /** @description Updated thread */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Thread"];
                    };
                };
                /** @description Forbidden — agent token may not access this thread */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Thread not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/threads/{threadId}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List messages in a thread */
        get: {
            parameters: {
                query?: {
                    limit?: string;
                    offset?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of messages with pagination info */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MessageListResponse"];
                    };
                };
                /** @description Thread not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create a message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateMessageBody"];
                };
            };
            responses: {
                /** @description Created message */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Thread not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Attachment exceeds size limit */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/messages/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim the next unclaimed user message in a thread */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Claimed message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                /** @description Thread not found, or no unclaimed messages in thread */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/messages/{id}/attachment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream a message's attachment (ephemeral — cleared after read) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Attachment bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/octet-stream": string;
                    };
                };
                /** @description Thread not found, message not found, or no attachment */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/threads/{threadId}/messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a message by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                /** @description Thread or message not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a message */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                /** @description Thread or message not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a message */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateMessageBody"];
                };
            };
            responses: {
                /** @description Updated message */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Message"];
                    };
                };
                /** @description Thread or message not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/threads/{threadId}/messages/{id}/reply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post an agent reply to a user message */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ReplyBody"];
                };
            };
            responses: {
                /** @description User message and the newly created assistant reply */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ReplyResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Thread or message not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Message already has a reply */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ChatToken: {
            /** @example clxtoken123456 */
            id: string;
            /** @example ci-runner */
            label?: string | null;
            /** @example agent-id-123 */
            agentId?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example null
             */
            revokedAt?: string | null;
        };
        Error: {
            /** @example not found */
            error: string;
        };
        ChatTokenWithRaw: components["schemas"]["ChatToken"] & {
            /** @example raw-token-value-shown-once */
            rawToken: string;
        };
        TokenBody: {
            /** @example ci-runner */
            label?: string;
            /** @example agent-id-123 */
            agentId?: string;
        };
        Thread: {
            /** @example clxthread123456 */
            id: string;
            /** @example agent-id-123 */
            agentId: string;
            /** @example member-id-123 */
            memberId?: string | null;
            /** @example Deployment question */
            title?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-06T12:00:00.000Z
             */
            updatedAt: string;
        };
        ThreadListResponse: {
            threads: components["schemas"]["Thread"][];
            /** @example 10 */
            total: number;
            /** @example 50 */
            limit: number;
            /** @example 0 */
            offset: number;
        };
        CreateThreadBody: {
            /** @example agent-id-123 */
            agentId: string;
            /** @example member-id-123 */
            memberId?: string;
            /** @example Deployment question */
            title?: string;
        };
        ThreadStats: {
            /** @example 5 */
            messageCount: number;
            /** @example 100 */
            totalInputTokens: number;
            /** @example 200 */
            totalOutputTokens: number;
            /** @example 0.05 */
            totalCostUsd: number;
        };
        UpdateThreadBody: {
            /** @example New title */
            title?: string | null;
            /** @example member-id-123 */
            memberId?: string | null;
        };
        Message: {
            /** @example clxmessage123456 */
            id: string;
            /** @example clxthread123456 */
            threadId: string;
            /**
             * @example user
             * @enum {string}
             */
            role: "user" | "assistant";
            /** @example How do I deploy this? */
            body: string;
            /**
             * @example {
             *       "input_tokens": 10,
             *       "output_tokens": 20
             *     }
             */
            tokens?: {
                [key: string]: unknown;
            } | null;
            /** @example 0.02 */
            costUsd?: number | null;
            /** @example screenshot.png */
            attachmentFilename?: string | null;
            /** @example 1024 */
            attachmentSize?: number | null;
            /**
             * @default false
             * @example false
             */
            claimed: boolean;
            /**
             * Format: date-time
             * @example null
             */
            claimedAt?: string | null;
            /** @example agent-id-123 */
            claimedBy?: string | null;
            /**
             * Format: date-time
             * @example null
             */
            repliedAt?: string | null;
            /** @example null */
            errorKind?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
        };
        MessageListResponse: {
            messages: components["schemas"]["Message"][];
            /** @example 10 */
            total: number;
            /** @example 50 */
            limit: number;
            /** @example 0 */
            offset: number;
        };
        CreateMessageBody: {
            /**
             * @example user
             * @enum {string}
             */
            role?: "user" | "assistant";
            /** @example How do I deploy this? */
            body?: string;
            /**
             * @example {
             *       "input_tokens": 10,
             *       "output_tokens": 20
             *     }
             */
            tokens?: {
                [key: string]: unknown;
            };
            /** @example 0.02 */
            costUsd?: number;
            /** @example screenshot.png */
            attachmentFilename?: string;
            /** @example 1024 */
            attachmentSize?: number;
            /** @example base64-encoded-bytes */
            attachmentBytes?: string;
        };
        UpdateMessageBody: {
            /** @example Updated text */
            body?: string;
            /**
             * @example {
             *       "input_tokens": 10,
             *       "output_tokens": 20
             *     }
             */
            tokens?: {
                [key: string]: unknown;
            } | null;
            /** @example 0.03 */
            costUsd?: number | null;
            /** @example null */
            errorKind?: string | null;
        };
        ReplyResponse: {
            userMessage: components["schemas"]["Message"];
            assistantMessage: components["schemas"]["Message"];
        };
        ReplyBody: {
            /** @example Sure, here is the answer. */
            body?: string;
            /**
             * @example {
             *       "input_tokens": 10,
             *       "output_tokens": 20
             *     }
             */
            tokens?: {
                [key: string]: unknown;
            };
            /** @example 0.02 */
            costUsd?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
