/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks */
        get: {
            parameters: {
                query?: {
                    status?: string;
                    state?: "open" | "closed" | "in_progress" | "ready" | "blocked";
                    session?: string;
                    repo?: string;
                    assignee?: string;
                    claimedBy?: string;
                    branch?: string;
                    pr?: string;
                    limit?: string;
                    offset?: string;
                    ready?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of tasks with total count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskListResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create a task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CreateTaskBody"];
                };
            };
            responses: {
                /** @description Created task */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk insert tasks */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["BulkInsertBody"];
                };
            };
            responses: {
                /** @description Bulk insert result */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BulkInsertResponse"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/distinct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get distinct session and repo values */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Distinct values */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DistinctResponse"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a task by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a task */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update a task */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UpdateTaskBody"];
                };
            };
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/tasks/{id}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomically claim a task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ClaimBody"];
                };
            };
            responses: {
                /** @description Claimed task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict — already claimed */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Touch heartbeatAt on a claimed task */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a task as done */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/fail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a task as blocked */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["FailBody"];
                };
            };
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release a task back to pending */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Updated task */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Task"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all tokens */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Array of token metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskToken"][];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        /** Create a new token — raw value returned exactly once */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TokenBody"];
                };
            };
            responses: {
                /** @description Created token including the one-time raw value */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskTokenWithRaw"];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke a token */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Revoked token metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskToken"];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update token label and/or agentId */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["TokenBody"];
                };
            };
            responses: {
                /** @description Updated token metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TaskToken"];
                    };
                };
                /** @description Bad request — token is revoked */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Forbidden — admin token required */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Token not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pull requests */
        get: {
            parameters: {
                query?: {
                    repo?: string;
                    prNumber?: string;
                    taskId?: string;
                    state?: "open" | "merged" | "closed";
                    reviewState?: "pending" | "in_progress" | "posted" | "approved";
                    staged?: "true" | "false";
                    limit?: string;
                    offset?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of pull requests */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PrListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prs/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a pull request (atomic) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ClaimPrBody"];
                };
            };
            responses: {
                /** @description Updated existing claim */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
                /** @description New claim created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Conflict — already claimed with same commitSha */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prs/claim-next": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Atomic find-and-claim of oldest eligible PR */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["ClaimNextBody"];
                };
            };
            responses: {
                /** @description PR claimed — returns {pr, phase} */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ClaimNextResponse"];
                    };
                };
                /** @description No eligible PR found */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single pull request */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Pull request record */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update pull request fields */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdatePrBody"];
                };
            };
            responses: {
                /** @description Updated pull request */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
                /** @description Bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/prs/{id}/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Touch heartbeatAt for a claimed PR */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PR with updated heartbeatAt */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prs/{id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark PR review as complete (reviewState=posted) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Completed PR */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prs/{id}/patch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Increment patchCycles and conditionally reset reviewState=pending */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["PatchPrBody"];
                };
            };
            responses: {
                /** @description Patched PR */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/prs/{id}/release": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Release a claim (reviewState=pending, claimedBy cleared) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Released PR */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PullRequest"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Task: {
            /** @example clx1234567890 */
            id: string;
            /** @example Implement feature X */
            title: string;
            /**
             * @example pending
             * @enum {string}
             */
            status: "pending" | "in_progress" | "pr_open" | "approved" | "merged" | "done" | "deploying" | "deployed" | "blocked" | "cancelled";
            /** @example manual */
            source?: string | null;
            /** @example session-123 */
            session?: string | null;
            /** @example org/repo */
            repo?: string | null;
            /** @example Task description */
            description?: string | null;
            /**
             * @example [
             *       "Criterion 1",
             *       "Criterion 2"
             *     ]
             */
            acceptanceCriteria?: string[];
            /** @example feature */
            layer?: string | null;
            /** @example feat/feature-x */
            branch?: string | null;
            /**
             * @example [
             *       "task-1",
             *       "task-2"
             *     ]
             */
            dependencies?: string[];
            /** @example 42 */
            pr?: number | null;
            /** @example 5.5 */
            hours?: number | null;
            /** @example 2026-01-01T00:00:00.000Z */
            addedAt?: string | null;
            /** @example 2026-01-02T00:00:00.000Z */
            startedAt?: string | null;
            /** @example 2026-01-03T00:00:00.000Z */
            prCreatedAt?: string | null;
            /** @example 2026-01-04T00:00:00.000Z */
            mergedAt?: string | null;
            /** @example null */
            blockedAt?: string | null;
            /** @example Waiting on dependency */
            blockedReason?: string | null;
            /** @example Some notes */
            note?: string | null;
            /** @example feature */
            type?: string | null;
            /** @example high */
            priority?: string | null;
            /** @example null */
            cancelledAt?: string | null;
            /** @example 2026-01-05T00:00:00.000Z */
            completedAt?: string | null;
            /** @example null */
            deployingAt?: string | null;
            /** @example 2026-01-06T00:00:00.000Z */
            deployedAt?: string | null;
            /** @example 2 */
            ciFixAttempts?: number | null;
            /** @example abc123def456 */
            mergeCommit?: string | null;
            /** @example https://github.com/org/repo/pull/42 */
            prUrl?: string | null;
            /** @example user@example.com */
            assignee?: string | null;
            /** @example GH-123 */
            issue?: string | null;
            /** @example sonnet */
            model?: string | null;
            /** @example 7 */
            complexity?: number | null;
            /** @example true */
            hitl?: boolean | null;
            /** @example 2026-01-02T00:00:00.000Z */
            hitlNotifiedAt?: string | null;
            /** @example agent-id-123 */
            claimedBy?: string | null;
            /** @example prefer-sonnet */
            agentHint?: string | null;
            /** @example 2026-01-02T00:00:00.000Z */
            claimedAt?: string | null;
            /** @example 2026-01-06T12:00:00.000Z */
            heartbeatAt?: string | null;
            /** @example 10 */
            simplifyTotal?: number | null;
            /** @example 2 */
            simplifyDry?: number | null;
            /** @example 3 */
            simplifyDeadCode?: number | null;
            /** @example 1 */
            simplifyNaming?: number | null;
            /** @example 2 */
            simplifyComplexity?: number | null;
            /** @example 2 */
            simplifyConsistency?: number | null;
            /** @example 5.5 */
            coverageDelta?: number | null;
            /** @example medium */
            effortLevel?: string | null;
            /** @example 1000 */
            inputTokens?: number | null;
            /** @example 500 */
            outputTokens?: number | null;
            /** @example 100 */
            cacheReadTokens?: number | null;
            /** @example 50 */
            cacheCreationTokens?: number | null;
            /** @example 0.02 */
            costUsd?: number | null;
            /**
             * @example {
             *       "customKey": "customValue"
             *     }
             */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-06T12:00:00.000Z
             */
            updatedAt: string;
        };
        TaskListResponse: {
            tasks: components["schemas"]["Task"][];
            /** @example 10 */
            total: number;
        };
        Error: {
            /** @example not found */
            error: string;
        };
        CreateTaskBody: {
            /** @example Implement feature X */
            title?: string;
            /** @example pending */
            status?: string;
            /** @example org/repo */
            repo?: string | null;
            /** @example session-123 */
            session?: string;
            /** @example Task description */
            description?: string;
            /** @example service */
            layer?: string;
            /** @example feat/feature-x */
            branch?: string;
            /** @example [] */
            dependencies?: string[];
            /** @example [] */
            acceptanceCriteria?: string[];
            /** @example user@example.com */
            assignee?: string;
            /** @example high */
            priority?: string;
            /** @example feature */
            type?: string;
            /** @example manual */
            source?: string;
        };
        BulkInsertResponse: {
            /** @example 3 */
            inserted: number;
            /** @example 1 */
            updated: number;
        };
        BulkInsertBody: {
            /** @example Implement feature X */
            title?: string;
            /** @example pending */
            status?: string;
            /** @example org/repo */
            repo?: string | null;
        }[];
        DistinctResponse: {
            /**
             * @example [
             *       "session-1"
             *     ]
             */
            sessions: string[];
            /**
             * @example [
             *       "org/repo"
             *     ]
             */
            repos: string[];
        };
        UpdateTaskBody: {
            [key: string]: unknown;
        };
        ClaimBody: {
            /** @example agent-id-123 */
            claimedBy?: string;
        };
        FailBody: {
            /** @example build failed */
            reason?: string;
        };
        TaskToken: {
            /** @example clxtoken123456 */
            id: string;
            /** @example ci-runner */
            label?: string | null;
            /** @example agent-id-123 */
            agentId?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example null
             */
            revokedAt?: string | null;
        };
        TaskTokenWithRaw: components["schemas"]["TaskToken"] & {
            /** @example raw-token-value-shown-once */
            rawToken: string;
        };
        TokenBody: {
            /** @example ci-runner */
            label?: string;
            /** @example agent-id-123 */
            agentId?: string;
        };
        PullRequest: {
            /** @example clx0987654321 */
            id: string;
            /** @example org/repo */
            repo: string;
            /** @example 42 */
            prNumber: number;
            /** @example clx1234567890 */
            taskId?: string | null;
            /**
             * @default false
             * @example false
             */
            staged: boolean;
            /**
             * @default open
             * @example open
             * @enum {string}
             */
            state: "open" | "merged" | "closed";
            /**
             * @default pending
             * @example pending
             * @enum {string}
             */
            reviewState: "pending" | "in_progress" | "posted" | "approved";
            /** @example abc123def456 */
            commitSha?: string | null;
            /**
             * @default 0
             * @example 1
             */
            patchCycles: number;
            /**
             * @default 0
             * @example 0
             */
            reviewCycles: number;
            /** @example agent-id-123 */
            agentId?: string | null;
            /** @example 2026-01-03T00:00:00.000Z */
            reviewedAt?: string | null;
            /** @example null */
            patchedAt?: string | null;
            /** @example null */
            mergedAt?: string | null;
            /**
             * @description ISO timestamp of the GitHub PR's actual creation time. Set once via POST /prs/claim (first claim only); read-only thereafter.
             * @example 2026-01-01T00:00:00.000Z
             */
            prCreatedAt?: string | null;
            /** @example agent-id-123 */
            claimedBy?: string | null;
            /** @example 2026-01-02T00:00:00.000Z */
            claimedAt?: string | null;
            /** @example 2026-01-06T12:00:00.000Z */
            heartbeatAt?: string | null;
            /**
             * @example review
             * @enum {string|null}
             */
            phase?: "review" | "patch" | "deploy" | null;
            /** @example 2026-01-02T00:00:00.000Z */
            readyForReviewAt?: string | null;
            /** @example null */
            readyForPatchAt?: string | null;
            /** @example null */
            readyForDeployAt?: string | null;
            /**
             * Format: date-time
             * @example 2026-01-01T00:00:00.000Z
             */
            createdAt: string;
            /**
             * Format: date-time
             * @example 2026-01-06T12:00:00.000Z
             */
            updatedAt: string;
        };
        PrListResponse: {
            /** @description Array of pull requests */
            prs: components["schemas"]["PullRequest"][];
            /** @example 1 */
            total: number;
            /** @example 50 */
            limit: number;
            /** @example 0 */
            offset: number;
        };
        ClaimPrBody: {
            /**
             * @description Repository in org/repo format
             * @example org/repo
             */
            repo: string;
            /**
             * @description Pull request number
             * @example 42
             */
            prNumber: number;
            /**
             * @description Commit SHA to associate
             * @example abc123def456
             */
            commitSha: string;
            /**
             * @description Agent claiming this PR (admin tokens only)
             * @example agent-id-123
             */
            claimedBy?: string;
            /**
             * @description Associated task ID
             * @example clx1234567890
             */
            taskId?: string;
            /**
             * @description Pipeline phase this claim is for (defaults to 'review' when omitted)
             * @example patch
             * @enum {string}
             */
            phase?: "review" | "patch" | "deploy";
            /**
             * @description ISO timestamp of the GitHub PR's actual creation time. Only applied on first claim (record creation); ignored on subsequent claims since the field is immutable once set.
             * @example 2026-01-01T00:00:00.000Z
             */
            prCreatedAt?: string;
        };
        ClaimNextResponse: {
            pr: components["schemas"]["PullRequest"];
            /**
             * @example review
             * @enum {string}
             */
            phase: "review" | "patch" | "deploy";
        };
        ClaimNextBody: {
            /**
             * @description Agent ID (admin tokens only; agent tokens use token identity)
             * @example agent-id-123
             */
            agentId?: string;
            /**
             * @description Maximum concurrent PRs to claim
             * @example 1
             */
            maxConcurrent?: number;
        };
        UpdatePrBody: {
            [key: string]: unknown;
        };
        PatchPrBody: {
            /**
             * @description Current head commit SHA. When provided and it differs from the record's stored commitSha, reviewState resets to pending and commitSha is updated. When it matches, reviewState is left untouched (no-op patch cycle). When omitted, reviewState unconditionally resets to pending (legacy behavior).
             * @example abc123def456
             */
            commitSha?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
